# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
---
version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - modernize
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
