package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/chainguard-dev/clog"
	"github.com/chainguard-dev/terraform-provider-imagetest/cmd/instgen/emitter"
)

type instance struct {
	SKU     string  `json:"-"`
	Type    string  `json:"type"`
	PerHour float32 `json:"per_hour"`
}

func (self *instance) Reset() {
	self.SKU = ""
	self.Type = ""
	self.PerHour = 0
}

type object = map[string]any

const fileModeRWX = 0o700
const fileModeRW = 0o600
const fileFlagsOverwrite = os.O_TRUNC | os.O_CREATE | os.O_WRONLY

func main() {
	// Log with file name + line number
	log.SetFlags(log.Lshortfile)
	slog.SetLogLoggerLevel(slog.LevelDebug)
	log := clog.NewLogger(slog.Default())

	// Init the application-wide context
	//
	// This is really only used for HTTP requests
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Parse command-line inputs
	args := parseArgs()
	log.Info("selected AWS region", "region", args.Region)
	log.Info(
		"output constraints identified",
		"package_name", args.PackageName,
		"package_path", args.PackagePath,
		"file_name", args.FileName,
	)

	// If the output directory doesn't exist, try to make it
	err := os.MkdirAll(args.PackagePath, fileModeRWX)
	if err != nil && !errors.Is(err, os.ErrExist) {
		log.Fatal(
			"failed to craete output package directory",
			"path", args.PackagePath,
			"error", err,
		)
	}

	// Open a writable stream to the output file
	outputPath := filepath.Join(args.PackagePath, args.FileName)
	f, err := os.OpenFile(outputPath, fileFlagsOverwrite, fileModeRW)
	if err != nil {
		log.Fatal(
			"failed to open writable stream to output file",
			"path", outputPath, "error", err,
		)
	}
	defer f.Close()

	// Init the request
	const urlFmt = "https://pricing.us-east-1.amazonaws.com" +
		"/offers/v1.0/aws/AmazonEC2/current/" +
		"%s" /* Region */ +
		"/index.json"
	var url = fmt.Sprintf(urlFmt, args.Region)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		log.Fatal("failed to init GET request", "error", err)
	}

	// Get the response
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal("failed to execute GET request", "error", err)
	} else if res.StatusCode >= http.StatusBadRequest {
		log.Fatal("HTTP GET request failed", "status_code", res.StatusCode)
	}

	// Unmarshal the response
	var results = map[string]any{}
	err = json.NewDecoder(res.Body).Decode(&results)
	if err != nil {
		log.Fatal("failed to decode JSON response", "error", err)
	}

	root := NewStackMap(results)

	const keyProducts = "products"
	products, err := root.Fork(keyProducts)
	if err != nil {
		log.Fatal(
			"failed to retrieve root map",
			"leaf", keyProducts,
			"error", err,
		)
	}

	const keyTerms = "terms"
	terms, err := root.Fork(keyTerms)
	if err != nil {
		log.Fatal(
			"failed to retrieve map object",
			"branch", products.String(),
			"leaf", keyTerms,
			"error", err,
		)
	}

	const keyOnDemand = "OnDemand"
	if err := terms.Push(keyOnDemand); err != nil {
		log.Fatal(
			"failed to extract map object",
			"branch", terms.String(),
			"leaf", keyTerms,
			"error", err,
		)
	}

	// Bootstrap the generated file
	e := emitter.New(f, "\t")
	e.Writeln("// GENERATED BY PLGEN. DO NOT EDIT.")
	e.Writefln("package %s", args.PackageName)
	e.Newline()
	e.Writefln("var PriceList = _PriceList{")
	e.In()

	i := &instance{}
	for k := range products.All() {
		i, err := populateInstance(i, k, products, terms)
		switch {
		case err == nil:
			log.Info(
				"found instance type",
				"sku", i.SKU,
				"type", i.Type,
				"cost", i.PerHour,
			)
			// Write the pricelist entry
			const largestColumn = 20
			e.Indent().Writefln("\"%s\":%-*s%.4f,", i.Type, 20-len(i.Type), "", i.PerHour)

		case errors.Is(err, ErrTenancyNotShared):
			log.Debug(
				"skipping dedicated instance",
				"instance_type", i.Type,
			)

		default:
			log.Error(
				"failed to identify price for instance",
				"instance_type", i.Type,
				"error", err,
			)
		}

		i.Reset()
	}

	// Wrap up the generated file
	e.Writeln("}")
	e.Newline()
}

const (
	kindObject = "object"
	kindString = "string"

	msgFailedExtract = "Failed to extract [%s] at [%s.%s]: %s."
)

func populateInstance(i *instance, sku string, products, onDemand *StackMap) (*instance, error) {

	//
	// Set the instance SKU
	//

	i.SKU = sku

	//
	// Set the instance type
	//

	if err := products.Push(sku); err != nil {
		return i, NewExtractError(sku, onDemand.String(), err)
	}
	defer products.Pop()

	const keyAttributes = "attributes"
	if err := products.Push(keyAttributes); err != nil {
		return i, NewExtractError(keyAttributes, onDemand.String(), err)
	}
	defer products.Pop()

	var err error
	const keyInstanceType = "instanceType"
	i.Type, err = products.GetString(keyInstanceType)
	if err != nil {
		return i, NewExtractError(keyInstanceType, onDemand.String(), err)
	}

	// Ignore non-shared tenancy instances (ex: dedicated hosts)
	const keyTenancy = "tenancy"
	const tenancyShared = "Shared"
	if v, err := products.GetString(keyTenancy); err != nil {
		return i, NewExtractError(keyTenancy, products.String(), err)
	} else if v != tenancyShared {
		return i, ErrTenancyNotShared
	}

	// Ignore reserved instance types
	const keyUsageType = "usagetype" // Not a typo, `t` is lowercase
	if v, err := products.GetString(keyUsageType); err != nil {
		return i, NewExtractError(keyUsageType, products.String(), err)
	} else if !strings.Contains(v, "-BoxUsage:") {
		return i, ErrReservedInstanceType
	}

	// Ignore non-Linux instance types
	const keyOS = "operatingSystem"
	if v, err := products.GetString(keyOS); err != nil {
		return i, NewExtractError(keyOS, products.String(), err)
	} else if v != "Linux" {
		return i, ErrNotLinux
	}

	// Ignore instances with pre-installed software
	const keyPreinstalledSW = "preInstalledSw"
	if v, err := products.GetString(keyPreinstalledSW); err != nil {
		return i, NewExtractError(keyPreinstalledSW, products.String(), err)
	} else if v != "NA" {
		return i, ErrHasPreinstalledSW
	}

	//
	// Set the instance type's per-hour cost
	//

	if err := onDemand.Push(sku); err != nil {
		return i, NewExtractError(sku, onDemand.String(), err)
	}
	defer onDemand.Pop()

	for k := range onDemand.All() {
		var v float32
		if v, err = instanceCost(onDemand, k); err == nil {
			i.PerHour = float32(v)
			return i, nil
		}
	}

	return i, err
}

func instanceCost(onDemand *StackMap, sku string) (float32, error) {
	var err error

	if err = onDemand.Push(sku); err != nil {
		return 0, NewExtractError(sku, onDemand.String(), err)
	}
	defer onDemand.Pop()

	const keyPriceDimensions = "priceDimensions"
	if err = onDemand.Push(keyPriceDimensions); err != nil {
		return 0, NewExtractError(sku, onDemand.String(), err)
	}
	defer onDemand.Pop()

	// Iterate price dimensions
	for k := range onDemand.All() {
		var v float32
		if v, err = dimensionCost(onDemand, k); err == nil {
			return v, nil
		}
	}

	return 0, err
}

func dimensionCost(onDemand *StackMap, dimension string) (float32, error) {
	if err := onDemand.Push(dimension); err != nil {
		return 0, NewExtractError(dimension, onDemand.String(), err)
	}
	defer onDemand.Pop()

	const keyPricePerUnit = "pricePerUnit"
	if err := onDemand.Push(keyPricePerUnit); err != nil {
		return 0, NewExtractError(keyPricePerUnit, onDemand.String(), err)
	}
	defer onDemand.Pop()

	const keyUSD = "USD"
	price, err := onDemand.GetString(keyUSD)
	if err != nil {
		return 0, NewExtractError(keyUSD, onDemand.String(), err)
	} else if strings.HasPrefix(price, "0") {
		return 0, fmt.Errorf("zero-dollar SKU")
	}

	cost, err := strconv.ParseFloat(price, 32)
	if err != nil {
		return 0, fmt.Errorf("failed to parse price [%s]: %w", price, err)
	}

	return float32(cost), nil
}
