// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type Feature struct {
	ID          string      `json:"id"`
	HarnessID   string      `json:"harness_id"`
	InventoryID string      `json:"inventory_id"`
	Labels      interface{} `json:"labels"`
}

type Harness struct {
	ID          string `json:"id"`
	InventoryID string `json:"inventory_id"`
}

type Inventory struct {
	ID string `json:"id"`
}
