package docker

import (
	"context"

	"github.com/moby/moby/api/types/mount"
	"github.com/moby/moby/client"
)

type VolumeRequest struct {
	// Name is the name of the volume to create, if empty a random name will be
	// generated by the daemon
	Name   string
	Target string
	Labels map[string]string
}

func (d *Client) CreateVolume(ctx context.Context, req *VolumeRequest) (mount.Mount, error) {
	if req.Labels == nil {
		req.Labels = make(map[string]string)
	}

	v, err := d.inner.VolumeCreate(ctx, client.VolumeCreateOptions{
		Name:   req.Name,
		Labels: req.Labels,
	})
	if err != nil {
		return mount.Mount{}, err
	}

	return mount.Mount{
		Type:   mount.TypeVolume,
		Source: v.Volume.Name,
		Target: req.Target,
		VolumeOptions: &mount.VolumeOptions{
			Labels: d.withDefaultLabels(req.Labels),
		},
	}, nil
}

func (d *Client) RemoveVolume(ctx context.Context, v mount.Mount) error {
	_, err := d.inner.VolumeRemove(ctx, v.Source, client.VolumeRemoveOptions{Force: true})
	return err
}
