package main

import (
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

const doNotEdit = "// GENERATED BY PLGEN. DO NOT EDIT."

func generatePriceList(pkgName, pkgPath, pkgFileName string, pl fmt.GoStringer) error {
	// Get a writable handle to the output file
	outputPath := filepath.Join(pkgPath, pkgFileName)
	f, err := os.OpenFile(outputPath, fileFlagsOverwrite, fileModeRW)
	if err != nil {
		log.Fatal(
			"failed to open writable stream to output file",
			"path", outputPath, "error", err,
		)
	}
	defer f.Close()

	var errs error
	// Write the 'DO NOT EDIT' header
	_, err = fmt.Fprintln(f, doNotEdit)
	errs = errors.Join(errs, err)
	// Write the package name
	_, err = fmt.Fprintf(f, "package %s\n", pkgName)
	errs = errors.Join(errs, err)
	// Write a buffer whitespace
	_, err = fmt.Fprintln(f)
	errs = errors.Join(errs, err)
	// Serialize the PriceList
	_, err = fmt.Fprintf(f, "var priceList = %#v", pl)
	errs = errors.Join(errs, err)

	return errs
}
